kind: pipeline
type: docker
name: default
steps:
    - name: build
      image: node
      commands:
          - npm config set registry http://mirrors.cloud.tencent.com/npm/
          - npm install -g pnpm
          - pnpm i
          - pnpm clear && pnpm build
    - name: upload
      image: appleboy/drone-scp
      settings:
          host:
              from_secret: host
          username:
              from_secret: username
          key:
              from_secret: ssh_key
          port: 22
          command_timeout: 2m
          target: /tmp/site
          source:
              - ./build
    - name: deploy
      image: appleboy/drone-ssh
      environment:
          DEPLOY_PATH:
              from_secret: deploy_path
      settings:
          host:
              from_secret: host
          username:
              from_secret: username
          key:
              from_secret: ssh_key
          port: 22
          command_timeout: 2m
          envs: [DEPLOY_PATH]
          script:
              - rm -rf $${DEPLOY_PATH}
              - mv /tmp/site/build $${DEPLOY_PATH}
